---
title: "featureEngineering"
author: "Priyanka Dutta"
date: "October 19, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This markdown concentrates on data cleaning and feature engineering

fix misleading NAs
```{r}
# not all NAs in taxdelinquencyyear are true NAs. Converting the right ones to 0
p16$taxdelinquencyyear[as.numeric(p16$taxdelinquencyflag)==1 & is.na(p16$taxdelinquencyyear)]=0
p17$taxdelinquencyyear[as.numeric(p17$taxdelinquencyflag)==1 & is.na(p17$taxdelinquencyyear)]=0

# not all NAs in fireplacecnt are true NAs. Converting the right ones to 0
p16$fireplacecnt[as.numeric(p16$fireplaceflag)==1 & is.na(p16$fireplacecnt)]=0
p17$fireplacecnt[as.numeric(p17$fireplaceflag)==1 & is.na(p17$fireplacecnt)]=0

p16$poolcnt[is.na(p16$poolcnt)]=0
p17$poolcnt[is.na(p17$poolcnt)]=0

p16$poolsizesum[is.na(p16$poolsizesum)]=0
p17$poolsizesum[is.na(p17$poolsizesum)]=0

p16$pooltypeid2[is.na(p16$pooltypeid2)]=0
p17$pooltypeid2[is.na(p17$pooltypeid2)]=0

p16$pooltypeid7[is.na(p16$pooltypeid7)]=0
p17$pooltypeid7[is.na(p17$pooltypeid7)]=0
```

delete redundant features (step2)
```{r}
# bathroomcnt, calculatedbathnbr and fullbathcnt are very similar. bathroomcnt has fewest NAs, so we will delete the other 2
p16 = subset(p16,select = -c(calculatedbathnbr,fullbathcnt))
p17 = subset(p17,select = -c(calculatedbathnbr,fullbathcnt))

# calculatedfinishedsquarefeet & finishedsquarefeet12 are the same, calculatedfinishedsquarefeet has fewer NAs. The other area features are also very correlated with calculatedfinishedsquarefeet while having many missing values
p16 = subset(p16,select = -c(finishedsquarefeet12,finishedsquarefeet13, finishedsquarefeet15,finishedsquarefeet6))
p17 = subset(p17,select = -c(finishedsquarefeet12,finishedsquarefeet13, finishedsquarefeet15,finishedsquarefeet6))

#finishedsquarefeet50 and finishedfloor1squarefeet are the exactly the same information according to the dictionary descriptions, lets remove finishedsquarefeet50 as it has more missing values
p16 = subset(p16,select = -c(finishedsquarefeet50))
p17 = subset(p17,select = -c(finishedsquarefeet50))

# roomcnt seems off
p16 = subset(p16,select = -c(roomcnt))
p17 = subset(p17,select = -c(roomcnt))

# cencustractandblock & rawcencustractandblock have the same info, latter has fewer NAs, deleting former
p16 = subset(p16,select = -c(censustractandblock))
p17 = subset(p17,select = -c(censustractandblock))

# pooltypeid10(does home have a Spa or hot tub) seems to be inconcistent with the 'hashottuborspa' field - these two fields should have the same information? Deleting 'pooltypeid10' as has more missing values
p16 = subset(p16,select = -c(pooltypeid10))
p17 = subset(p17,select = -c(pooltypeid10))
```

missing value imputation 1 (step 3)
```{r}
# taxvaluedollarcnt = structuretaxvaluedollarcnt + landtaxvaluedollarcnt, using this relation to impute some missing values exactly
# e.g: sum(is.na(p16$structuretaxvaluedollarcnt)) reduces from 54982 to 42550, and landtax from 67733 to 42550

p16$taxvaluedollarcnt[is.na(p16$taxvaluedollarcnt)]= p16$structuretaxvaluedollarcnt[is.na(p16$taxvaluedollarcnt)]+p16$landtaxvaluedollarcnt[is.na(p16$taxvaluedollarcnt)]

p16$structuretaxvaluedollarcnt[is.na(p16$structuretaxvaluedollarcnt)]= p16$taxvaluedollarcnt[is.na(p16$structuretaxvaluedollarcnt)]-p16$landtaxvaluedollarcnt[is.na(p16$structuretaxvaluedollarcnt)]

p16$landtaxvaluedollarcnt[is.na(p16$landtaxvaluedollarcnt)]= p16$taxvaluedollarcnt[is.na(p16$landtaxvaluedollarcnt)]-p16$structuretaxvaluedollarcnt[is.na(p16$landtaxvaluedollarcnt)]



p17$taxvaluedollarcnt[is.na(p17$taxvaluedollarcnt)]= p17$structuretaxvaluedollarcnt[is.na(p17$taxvaluedollarcnt)]+p17$landtaxvaluedollarcnt[is.na(p17$taxvaluedollarcnt)]

p17$structuretaxvaluedollarcnt[is.na(p17$structuretaxvaluedollarcnt)]= p17$taxvaluedollarcnt[is.na(p17$structuretaxvaluedollarcnt)]-p17$landtaxvaluedollarcnt[is.na(p17$structuretaxvaluedollarcnt)]

p17$landtaxvaluedollarcnt[is.na(p17$landtaxvaluedollarcnt)]= p17$taxvaluedollarcnt[is.na(p17$landtaxvaluedollarcnt)]-p17$structuretaxvaluedollarcnt[is.na(p17$landtaxvaluedollarcnt)]
```

additional features (part 4)
```{r}
library(data.table)
library(geosphere)

temp<-as.data.table(p16)
temp2<-as.data.table(p17)

# # setwd("C:/Work/Kaggle Competition/Zillow")
# 
# #prop_2016<-fread("properties_2016.csv")
# 
# 
# # Life of Property
# temp<-temp[,N_Age_of_Prop:=2018-yearbuilt,]
#
# # Average Room Size
# temp<-temp[,N_Avg_room_size:=calculatedfinishedsquarefeet/bedroomcnt,]
#
# # Ratio of built structure to land value
# temp<-temp[,N_structolandtaxratio:=mean(structuretaxvaluedollarcnt/landtaxvaluedollarcnt,na.rm=TRUE),]
# temp<-temp[,N_landtaxperunitarea:=landtaxvaluedollarcnt/lotsizesquarefeet,]
#
# # Average Tax by Geographies
# temp<-temp[,N_AvgLandtax.county:=mean(landtaxvaluedollarcnt/lotsizesquarefeet,na.rm=TRUE),by=c("regionidcounty")]
# temp<-temp[,N_AvgLandtax.zip:=mean(landtaxvaluedollarcnt/lotsizesquarefeet,na.rm=TRUE),by=c("regionidzip")]
# temp<-temp[,N_AvgLandtax.FIPS:=mean(landtaxvaluedollarcnt/lotsizesquarefeet,na.rm=TRUE),by=c("fips")]
#
# temp<-temp[,N_Avgtax.county:=mean(taxvaluedollarcnt,na.rm=TRUE),by=c("regionidcounty")]
# temp<-temp[,N_Avgtax.zip:=mean(taxvaluedollarcnt,na.rm=TRUE),by=c("regionidzip")]
# temp<-temp[,N_Avgtax.FIPS:=mean(taxvaluedollarcnt,na.rm=TRUE),by=c("fips")]
#
# temp<-temp[,N_NoofProps.county:=length(taxamount),by=c("regionidcounty")]
# temp<-temp[,N_NoofProps.zip:=length(taxamount),by=c("regionidzip")]
# temp<-temp[,N_NoofProps.FIPS:=length(taxamount),by=c("fips")]
#
# p16 = as.data.frame(temp)

# p16$new.taxratio = p16$taxamount/p16$taxvaluedollarcnt
# p17$new.taxratio = p17$taxamount/p17$taxvaluedollarcnt

# p17$new.taxarea = p17$structuretaxvaluedollarcnt/p17$calculatedfinishedsquarefeet

```

remove features missing more than 98% data
```{r}
mis16 = sapply(1:dim(p16)[2], function(j) 100*sum(is.na(p16[,j]))/dim(p16)[1])
mis17 = sapply(1:dim(p17)[2], function(j) 100*sum(is.na(p17[,j]))/dim(p17)[1])

# misssing % slightly different in 16 & 17, but similar. same features are more than 90% missing, removed
#cbind(mis16,mis17)

p16 = p16[,-which(mis16>98), drop = F]
p17 = p17[,-which(mis17>98), drop = F]
```

zip code encoding 1
```{r}
library(data.table)

temp<-as.data.table(p16)
temp2<-as.data.table(p17)

temp<-temp[,new.calcfinsqft.zip:=mean(calculatedfinishedsquarefeet,na.rm=TRUE),by=c("regionidzip")]
temp2<-temp2[,new.calcfinsqft.zip:=mean(calculatedfinishedsquarefeet,na.rm=TRUE),by=c("regionidzip")]

p16 = as.data.frame(temp)
p17 = as.data.frame(temp2)

rm(temp,temp2)

p16 = subset(p16, select = -c(regionidzip))
p17 = subset(p17, select = -c(regionidzip))
```

transaction date to month (1-24)
```{r}
library(lubridate)
t16$month = month(as.POSIXlt(t16$transactiondate, format="%m/%d/%Y"))
t17$month = month(as.POSIXlt(t17$transactiondate, format="%Y-%m-%d")) + 12
```

identify multiclass categorical features, out-of-fold average
```{r}
col = intersect(colnames(p16), c("fips","propertycountylandusecode","propertylandusetypeid","propertyzoningdesc","rawcensustractandblock","regionidcity","regionidcounty","regionidzip","censustractandblock","heatingorsystemtypeid","airconditioningtypeid", "architecturalstyletypeid", "buildingclasstypeid", "decktypeid", "fireplaceflag", "hashottuborspa", "pooltypeid10", "pooltypeid2", "pooltypeid7", "regionidneighborhood", "storytypeid", "typeconstructiontypeid","taxdelinquencyflag"))

p16[col] = lapply(p16[col], factor)
p17[col] = lapply(p17[col], factor)

# simple numeric encoding
p16[col] = lapply(p16[col], as.numeric)
p17[col] = lapply(p17[col], as.numeric)

# out-of-fold average for high cardinality features
library(data.table)
library(dplyr)

master = left_join(p16,tran16,by = "parcelid")

for (i in 1:length(col)){
  #tmp = length(unique(unlist(master[col[i]])))
  tmp = ave(master$logerror, unlist(master[col[i]]), FUN = function(x) mean(x, na.rm = T))
  tmp[is.na(master[col[i]])] = NA
  master[paste(col[i],"new",sep = ".")] = tmp*runif(dim(master)[1],.98,1.02)
}
master = master[ , !(names(master) %in% col)]

master2 = left_join(p17,tran17,by = "parcelid")

for (i in 1:length(col)){
  #tmp = length(unique(unlist(master[col[i]])))
  tmp = ave(master2$logerror, unlist(master2[col[i]]), FUN = function(x) mean(x, na.rm = T))
  tmp[is.na(master2[col[i]])] = NA
  master2[paste(col[i],"new",sep = ".")] = tmp*runif(dim(master2)[1],.98,1.02)
}
master2 = master2[ , !(names(master2) %in% col)]

```

